spring.application.name=Backend
spring.datasource.url=jdbc:mysql://localhost:3306/aiquizapp
spring.datasource.username=root
spring.datasource.password=shj@8177#jw
//server.port=5077
spring.jpa.hibernate.ddl-auto=update

spring.datasource.name=aiquizapp
# Google AI Studio (Gemini) API key
gemini.api.key=AIzaSyC7dt0sDUW5JhE6-jSqplKI0ecVONPdVTM

# Choose the Gemini model you want to use
spring.ai.google.ai.chat.options.model=gemini-2.5-flash
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
#spring.jpa.generate-ddl=true
spring.jpa.open-in-view= false
spring.security.user.name=admin
spring.security.user.password=admin
